### ISSUE TITLE
孙子，我淘宝上又卖star，别不服

### ISSUE THREAD

**Issue by zizhangvzoc** [yulingtianxia/FuckFakeGitHubStars#3]

**Comment by zizhangvzoc** [comment]
前2季度低价， 欢迎来买， https://shop114509823.taobao.com/
安全放心， 已经卖了几万个，童叟无欺

**Comment by zizhangvzoc** [comment]
![图片](https://user-images.githubusercontent.com/49508193/55931576-ad8bab80-5c58-11e9-8ccb-c65433ac6e7e.png)

**Comment by Naville** [comment]
哇嗷，楼主真的好棒棒哦

**Comment by Naville** [comment]
看了一下交易记录，哇噻这行这么赚钱，一下能赚2700块钱，楼主能不能教教我怎么一起利用这个技术赚钱啊

**Comment by Naville** [comment]
毕竟，我还从来没有拿过这么低的工资
